'use client'
import { useI18n } from '@/lib/i18n'
import { LegalLayout } from '@/components/ui/legal-layout'

export default function CGUPage() {
  const { locale } = useI18n()
  const isFr = locale === 'fr'

  return (
    <LegalLayout
      title={isFr ? "Conditions Générales d'Utilisation" : "Terms of Use"}
      lastUpdated={isFr ? "Dernière mise à jour : 1er mars 2026" : "Last updated: March 1, 2026"}
    >
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 1 — Objet' : 'Article 1 — Purpose'}</h2>
        <p>{isFr
          ? "Les présentes Conditions Générales d'Utilisation (« CGU ») définissent les modalités d'utilisation de la plateforme MISEN (misen-ten.vercel.app), éditée par Steve Moradel."
          : "These Terms of Use define the conditions for using the MISEN platform (misen-ten.vercel.app), published by Steve Moradel."}</p>
        <p className="mt-2">{isFr
          ? "MISEN est un studio de production cinématographique assisté par intelligence artificielle permettant l'analyse de scénarios, la génération de prompts optimisés et l'organisation de projets de production."
          : "MISEN is an AI-assisted cinematographic production studio enabling script analysis, optimized prompt generation, and production project management."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 2 — Acceptation' : 'Article 2 — Acceptance'}</h2>
        <p>{isFr
          ? "L'accès et l'utilisation de la Plateforme impliquent l'acceptation pleine et entière des présentes CGU. En créant un compte, l'Utilisateur reconnaît avoir lu et accepté les présentes CGU."
          : "Access and use of the Platform implies full acceptance of these Terms. By creating an account, the User acknowledges having read and accepted these Terms."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 3 — Services' : 'Article 3 — Services'}</h2>
        <p>{isFr
          ? "MISEN propose : l'analyse de scénarios par 17 moteurs IA spécialisés, la génération de prompts optimisés pour chaque modèle vidéo IA, un assistant scénariste IA, des outils de pré-production (timeline, storyboard, copilote), et l'export en 6 formats."
          : "MISEN offers: script analysis by 13 specialized AI engines, optimized prompt generation for each AI video model, an AI screenwriting assistant, pre-production tools (timeline, storyboard, copilot), and export in 6 formats."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 4 — Compte utilisateur' : 'Article 4 — User Account'}</h2>
        <p>{isFr
          ? "L'inscription nécessite une adresse email valide et un mot de passe d'au moins 8 caractères. L'Utilisateur est responsable de la confidentialité de ses identifiants. L'Utilisateur peut supprimer son compte à tout moment depuis les paramètres."
          : "Registration requires a valid email address and a password of at least 8 characters. The User is responsible for keeping their credentials confidential. The User may delete their account at any time from the settings."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 5 — Propriété intellectuelle' : 'Article 5 — Intellectual Property'}</h2>
        <p>{isFr
          ? "L'Utilisateur conserve la propriété de ses scénarios et contenus. Les prompts générés par MISEN sont librement utilisables. Le code source, les moteurs d'analyse et la marque MISEN restent la propriété de Steve Moradel / Jabrilia Éditions."
          : "Users retain ownership of their scripts and content. Prompts generated by MISEN are freely usable. Source code, analysis engines, and the MISEN brand remain the property of Steve Moradel / Jabrilia Éditions."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 6 — Responsabilité' : 'Article 6 — Liability'}</h2>
        <p>{isFr
          ? "MISEN fournit un service d'aide à la production cinématographique. Les résultats d'analyse et les prompts générés sont fournis à titre indicatif. L'Éditeur ne saurait être tenu responsable de l'utilisation faite des prompts ou des vidéos générées par des modèles tiers."
          : "MISEN provides a cinematographic production assistance service. Analysis results and generated prompts are provided for informational purposes. The Publisher cannot be held responsible for the use made of prompts or videos generated by third-party models."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 7 — Données personnelles' : 'Article 7 — Personal Data'}</h2>
        <p>{isFr
          ? "Le traitement des données personnelles est détaillé dans notre Politique de Confidentialité. L'Utilisateur dispose d'un droit d'accès, de rectification, de suppression et de portabilité de ses données."
          : "Personal data processing is detailed in our Privacy Policy. Users have the right to access, rectify, delete, and export their data."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 8 — Modification des CGU' : 'Article 8 — Modification'}</h2>
        <p>{isFr
          ? "L'Éditeur se réserve le droit de modifier les présentes CGU. Les Utilisateurs seront informés de toute modification substantielle."
          : "The Publisher reserves the right to modify these Terms. Users will be informed of any substantial changes."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 9 — Droit applicable' : 'Article 9 — Governing Law'}</h2>
        <p>{isFr
          ? "Les présentes CGU sont régies par le droit français. Tout litige sera soumis à la juridiction des tribunaux compétents de Paris."
          : "These Terms are governed by French law. Any dispute shall be submitted to the jurisdiction of the competent courts of Paris."}</p>
      </section>
      <section>
        <h2 className="text-lg font-semibold text-white mb-3">{isFr ? 'Article 10 — Contact' : 'Article 10 — Contact'}</h2>
        <p>{isFr
          ? "Pour toute question relative aux présentes CGU : contact@jabrilia.com"
          : "For any questions regarding these Terms: contact@jabrilia.com"}</p>
      </section>
    </LegalLayout>
  )
}
